# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install Flask
    - pip install Flask-Script
    - pip install Flask-SQLAlchemy
    - pip install gunicorn
    - pip install requests
    - pip install coverage
    - pip install numpy
    - pip install -r app/requirments.txt

before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    - make status
    - ls -al
    - make check

notifications:
  slack: booksweepers:5JFI2w3n1TQousAyljODwLua
  on_success: always
  on_failure: always
