FORMAT: 1A
HOST: http://ibdb.me
# IBDB API
IBDB API is an API that allows users to get books and authors information.
## Books [/books]
### Get a list of all books [GET]
+ Response 200 (application/json)
        [
            {
                "id": 1,
                "isbn": "9780425256763",
                "title": "FIRE TOUCHED",
                "summary": "The shape-shifter Mercy Thompson and her Alpha werewolf mate, Adam, protect a stolen human child.",
                "best_seller_date": "2016-03-12",
                "best_seller_list": "Combined Print and E-Book Fiction",
                "book_image": "http:\/\/du.ec2.nytimes.com.s3.amazonaws.com\/prd\/books\/9780698180918.jpg",
                "author_id": 1,
                "publisher": "Ace",
                "author": []
            }
        ]
        
## Single Book [/books/{book_id}]
+ Parameters
    + book_id (number) - Unique id of the book requested
    
### Get a single book [GET]
+ Response 200 (application/json)
        {
            "id": 1,
            "isbn": "9780425256763",
            "title": "FIRE TOUCHED",
            "summary": "The shape-shifter Mercy Thompson and her Alpha werewolf mate, Adam, protect a stolen human child.",
            "best_seller_date": "2016-03-12",
            "best_seller_list": "Combined Print and E-Book Fiction",
            "book_image": "http:\/\/du.ec2.nytimes.com.s3.amazonaws.com\/prd\/books\/9780698180918.jpg",
            "author_id": 1,
            "publisher": "Ace",
            "author": []
        }
        
## Authors [/authors]
### Get a list of authors [GET]
+ Response 200 (application/json)
        [
            {
                "id": 1
                "first_name": "Anthony"
                "last_name": "Doerr"
                "book_count": 1
                "best_seller_date": "2016-03-12"
                "Books": []
            }
        ]
        
## Single Author [/authors/{author_id}]
+ Parameters
    + author_id (number) - Unique id of the author requested
### Get a single author [GET]
+ Response 200 (application/json)
        {
            "id": 1
            "first_name": "Anthony"
            "last_name": "Doerr"
            "book_count": 1
            "best_seller_date": "2016-03-12"
            "Books": []
        }